---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-config
spec:
  storageClassName: photoprism-config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.20.0.3
    path: /volume1/Media/photoprismconfig
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: photoprism-config
  resources:
    requests:
      storage: 1Mi
