apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:we8K4pfCDnFYbxQGVZnirpzRNWs=,iv:XdflG/CTZeMJ60W8XKLoM2yeLP/1PgMUjhL5oFzFnPE=,tag:OXRPaI36gRvUBhPB40aQxA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:HeZz3VMgTXphdJ5zE2qYw3sG8LuOlWphnr/Nz2SeCP/Pt6ShqA==,iv:gqQYdThcxuogiaavPTZaSXZwUnv9CdbJCgtW3MasHGs=,tag:JhKkMNe266fiqjVUZSQqFw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:2aTsDwHNJhbvIO4b1t7/JL02NoN/S9lh,iv:n6JDDOtUVVYDFFIAesUEFSkUYHkfMH125kH2xFwxwts=,tag:YYQSDcjCSXXA8fScjT4iCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOWgwaEpmNVB2MnJhaVVC
            MVlRQ2QzeHVJd2pwMHZhUHdBdTFzMVRTY25NCjFYak9KU2pUam9SVUMxSE5sQ2dY
            SzVXUytyTzNPUHlyaEpLemlwQUxBSFkKLS0tIE5XbXRpbUJSandkWkNCemtQOC91
            SllaTWhIMXl2MCtOT3hEV0ZPeUJoSEEKaWBu5ORNBaSWqYk+PklmbwV3xgsQJ6L9
            mELfUNZaGdKK34/0O4YsoD45zDnMJYejigrvcC/q/AuMXM6NGe1KNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T10:41:47Z"
    mac: ENC[AES256_GCM,data:S3OSBmzglYaHrx107T+LplQ8gqx1FcxewOLUZPVgUms1BiUzTnOM2GawFfs6L4jL4No7AWudx3TMjoDb50DWhoy7VTOIip1LcsduHKEYJAyCPHg6SAUZSZpRD42bkxBwAnjFybHueBhbIA3T4VzzsUT8MB4efbx4hxSYle2gkFQ=,iv:Ksy3K31wE1r93s71QGip6uBPi2wHiM84mqee2qSeIHY=,tag:E36iK0fT0nbd4YC/LgVOmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
