---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:14.8-10
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  bootstrap:
    recovery:
      source: &previousCluster postgres-v7
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://postgresql/
      endpointURL: ${SECRET_S3_URL}
      serverName: &currentCluster postgres-v8
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secrets
          key: MINIO_ACCESS_KEY
        secretAccessKey:
          name: cloudnative-pg-secrets
          key: MINIO_SECRET_KEY
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: s3://postgresql/
        endpointURL: ${SECRET_S3_URL}
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-secrets
            key: MINIO_ACCESS_KEY
          secretAccessKey:
            name: cloudnative-pg-secrets
            key: MINIO_SECRET_KEY
