---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb16
  namespace: database
  annotations:
    io.cilium/lb-ipam-ips: "10.213.0.58"
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    role: primary
