---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate-secret
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: frigate-secret
  dataFrom:
    - find:
        path: FRIGATE_
