---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.12.0-beta5

    env:
      TZ: "${TIMEZONE}"
      LIBVA_DRIVER_NAME: i965
      FRIGATE_MQTT_PASSWORD: ${SECRET_MQTT_USER_PASSWORD}

    service:
      main:
        ports:
          http:
            port: &port 5000
          rtsp:
            enabled: true
            port: 8554

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/icon: mdi:cctv
        hosts:
          - host: &host "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    securityContext:
      privileged: true

    volumeClaimTemplates:
      - name: config
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block
        labels:
          snapshot.home.arpa/enabled: "true"

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: frigate-configmap
        subPath: config.yaml
        mountPath: /config/config.yml
        readOnly: true
      media:
        enabled: true
        existingClaim: frigate-nfs
        mountPath: /media
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        mountPath: /dev/shm

    nodeSelector:
      google.feature.node.kubernetes.io/coral: "true"
      intel.feature.node.kubernetes.io/gpu: "true"

    resources:
      requests:
        cpu: 10m
        memory: 1000Mi
        gpu.intel.com/i915: "1"
      limits:
        memory: 6000Mi
        gpu.intel.com/i915: "1"
