apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    SECRET_FRIGATE_NFS_PATH: ENC[AES256_GCM,data:nLr5NbtwYYO5nqESPiyBslFocbmGGQ==,iv:n3//2eEaj02jsoykx3qTVWUclfgwuWWmoGTYz0NG2AM=,tag:5fw1Y6yMOQxgo0RJWuPyxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ1JBOUQ3R0lVWjQ2cnZI
            RlByL1RnR2tkYnpvL2VzNldUUDBiYTFTNG1NCmprTDErRlplaE1XNm1mNkltT24x
            RFdpeG9lVEZ3VStpNUhXWTkvVExuaVkKLS0tIG1JQ1o4YlY2NHpKY2FvZHZlWVZo
            QlhqcElOSnd6eUNHRkVoU01YZ0xxY0EKPLza3W6GUIIlxaHqkmvGOVVjup9hfioZ
            k3XqNaf2L1U9gSviWAO01U7rT1adNmLke7SlbzqQ+KVuxy/VuznApA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-20T08:03:00Z"
    mac: ENC[AES256_GCM,data:YF2qzLYmjjMVOIanPojSKra/twEo/sCiwEDYLlvm8JYXrt+x4Z36lwJP8UIBn//sAU7JQdhp7wOHgiAW4maQHFJUd1LTHfqRtnmdDf5sRnXSqPHtKIodQLY27tG8+zvxkApqCbq0jKb//MRDQXP6qcSAmm8cS0y/muJuap05yzs=,iv:NKyTDwN5+ADlzlK30I3AIjU1E4JMXNbhJ4YknFlnYe0=,tag:rd7KSj/Ykd4eNr8oeP707Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
