# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    FRIGATE_RTSP_USERNAME: ENC[AES256_GCM,data:KfaQ8PdlMg==,iv:+mb4q92A3vmTwv/7J1EQFm6dkX4pdmcc68E34EwNcfw=,tag:ujQYFbvyLvCBK4EmNnAqug==,type:str]
    FRIGATE_TAPO_USERNAME: ENC[AES256_GCM,data:Dgfv6Lx+QIUKkA==,iv:ozMEbcz9J4CrztlUjqy+z5mIzBpqU6r76Jd/CrTsybM=,tag:Dn2l3J4b22iPhbiijyerSw==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:vQ9zp1rbXBQz,iv:+tiYtld8QdH9vidsVuz4u8XwmkVyzGiaC7bWwavbfpY=,tag:PIMC1vr8hhI4AwKssK4ctw==,type:str]
    FRIGATE_GARAGE_DOOR_CAMERA_HOST: ENC[AES256_GCM,data:dU1eoaTcxAuLwlIG+Q==,iv:y6ozE3M8R/oo7ddPbfoLWaPfaZqmWZydVKLgDprtItw=,tag:jzkGRZwBVC20nbQwdFOs3w==,type:str]
    FRIGATE_GARAGE_CAMERA_HOST: ENC[AES256_GCM,data:HcsPKEV2PLUHgj47bw==,iv:BmsVsF17RHJzIdpeEytMBu9CD8kCniGI744utIFb7ug=,tag:jpSA8d/ldbD6kNqspa/60A==,type:str]
    FRIGATE_MAX_CAMERA_HOST: ENC[AES256_GCM,data:hdorYJRkd5KuGQe8dg==,iv:ErU326lMZtWRQc3Pb5mih/BTie5PFuKfU9yiqD3Qc6Q=,tag:0dbytdWaLIz1HPxTHLoH2w==,type:str]
    FRIGATE_PLAYROOM_CAMERA_HOST: ENC[AES256_GCM,data:VLvXu23GJegL3Tjctg==,iv:vGadGTTENnD4b2y6Yo9ai3HmhngOymYenQEeTqUxM14=,tag:gAaXL9WWVtwvZs7M6GQBWA==,type:str]
    FRIGATE_ZARA_CAMERA_HOST: ENC[AES256_GCM,data:glaiY8zYAZTjQewKQg==,iv:a/ox5lmPFy4TF1JxANFlSPGUaLw8WlUMRm3p+YNZa6w=,tag:hIiQORR5TJbrHwEkbcvKnA==,type:str]
    FRIGATE_DOORBELL_HOST: ENC[AES256_GCM,data:WU4FQce1PZBxrGgWSw==,iv:HVBMXLXpoOqrNRvUPQ18BFDfkVBySW3ToWVb3GUbB5Q=,tag:Q723ddIDxYyVs8vQiphYvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS3EzZW54UTg3cG9RWmpY
            dmJPdWZVNTBocFY0ZWM0TFJWNTJhYmxhUDMwClV2a0N6Qys5K0JwQ2VWeTRpMmNU
            TzFueWh2NGZCRnpoajVkVk00Uzc0OW8KLS0tIGF1U1AvbURaSFpZUmVpbHVsVFlx
            TVhBcUVtWC9vUkRQSGpyRmRqK0kyQ1UKXlXdcITACiZpZrynJw0IcXf/sCVUwbnN
            QqGdCe4lDg7CjSBV0K28MFrjBbO+1FMyqMzWZdfJ1qWwYBZ9GaufDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-11T09:56:52Z"
    mac: ENC[AES256_GCM,data:9JMkvJejLEL/wuSbSDK4nG6HEn8kqkQeRtdC6ZK/nply8c4IyZ+S53776GkffNoO9VOg7tQY9ua9apUnuxfNaeZwUq4BK9wOH9H0vzcKVkkBxHUg4fo9fB2uH5gjffmrHHtAUvhx+cSIOt+YDA78aQzWzcrElwMpt4frjPkxk78=,iv:ihtFYrjbAFvvIvyrgTuoBHOP/p5fLikeVuKZFh22ITE=,tag:F8u0IbAzq5gvejSNKTVYzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
