# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    FRIGATE_RTSP_USERNAME: ENC[AES256_GCM,data:MdyTVSFWTzAScA==,iv:WTjMwY1VjMkVkzEfQ3W7rM49d2poa99Z5+/oUkxA6uI=,tag:6r81evJTgLzKKNbnlPU1LQ==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:vQ9zp1rbXBQz,iv:+tiYtld8QdH9vidsVuz4u8XwmkVyzGiaC7bWwavbfpY=,tag:PIMC1vr8hhI4AwKssK4ctw==,type:str]
    FRIGATE_ZARA_CAMERA_HOST: ENC[AES256_GCM,data:iXLkcwhihk3WAKyS1I0=,iv:db8pOxp1dN4doJCtepZT9o0w2MGSx5hlqW4oCvHY6/0=,tag:6mJcOIg3UIkPjoqHTV4W0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS3EzZW54UTg3cG9RWmpY
            dmJPdWZVNTBocFY0ZWM0TFJWNTJhYmxhUDMwClV2a0N6Qys5K0JwQ2VWeTRpMmNU
            TzFueWh2NGZCRnpoajVkVk00Uzc0OW8KLS0tIGF1U1AvbURaSFpZUmVpbHVsVFlx
            TVhBcUVtWC9vUkRQSGpyRmRqK0kyQ1UKXlXdcITACiZpZrynJw0IcXf/sCVUwbnN
            QqGdCe4lDg7CjSBV0K28MFrjBbO+1FMyqMzWZdfJ1qWwYBZ9GaufDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T03:33:08Z"
    mac: ENC[AES256_GCM,data:HPkZSySL/wX5aC6ep6bLMo5WgUc0RUbyURNj6s5d4NfylHWBps+BCMIraIPNzzv1Q+i6k0D3mt5JmVFHE3og5HYFSgsto/d9HVoFBHpA+7VWn/uoRYviAE3Jt1EZJy23SWhZH90M/E4pyp+IykeywrmEwN/gXwTBd+8BQi4PDv8=,iv:iEXRwUDuP/G/2beJ3WnrLwbcDGdCfJRg3cPc8qqnhg8=,tag:bYoj+MmnJf8O2iNyy9D2HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
