# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    FRIGATE_RTSP_USERNAME: ENC[AES256_GCM,data:KfaQ8PdlMg==,iv:+mb4q92A3vmTwv/7J1EQFm6dkX4pdmcc68E34EwNcfw=,tag:ujQYFbvyLvCBK4EmNnAqug==,type:str]
    FRIGATE_TAPO_USERNAME: ENC[AES256_GCM,data:Dgfv6Lx+QIUKkA==,iv:ozMEbcz9J4CrztlUjqy+z5mIzBpqU6r76Jd/CrTsybM=,tag:Dn2l3J4b22iPhbiijyerSw==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:vQ9zp1rbXBQz,iv:+tiYtld8QdH9vidsVuz4u8XwmkVyzGiaC7bWwavbfpY=,tag:PIMC1vr8hhI4AwKssK4ctw==,type:str]
    FRIGATE_ZARA_CAMERA_HOST: ENC[AES256_GCM,data:iXLkcwhihk3WAKyS1I0=,iv:db8pOxp1dN4doJCtepZT9o0w2MGSx5hlqW4oCvHY6/0=,tag:6mJcOIg3UIkPjoqHTV4W0w==,type:str]
    FRIGATE_GARAGE_DOOR_CAMERA_HOST: ENC[AES256_GCM,data:dU1eoaTcxAuLwlIG+Q==,iv:y6ozE3M8R/oo7ddPbfoLWaPfaZqmWZydVKLgDprtItw=,tag:jzkGRZwBVC20nbQwdFOs3w==,type:str]
    FRIGATE_GARAGE_CAMERA_HOST: ENC[AES256_GCM,data:HcsPKEV2PLUHgj47bw==,iv:BmsVsF17RHJzIdpeEytMBu9CD8kCniGI744utIFb7ug=,tag:jpSA8d/ldbD6kNqspa/60A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS3EzZW54UTg3cG9RWmpY
            dmJPdWZVNTBocFY0ZWM0TFJWNTJhYmxhUDMwClV2a0N6Qys5K0JwQ2VWeTRpMmNU
            TzFueWh2NGZCRnpoajVkVk00Uzc0OW8KLS0tIGF1U1AvbURaSFpZUmVpbHVsVFlx
            TVhBcUVtWC9vUkRQSGpyRmRqK0kyQ1UKXlXdcITACiZpZrynJw0IcXf/sCVUwbnN
            QqGdCe4lDg7CjSBV0K28MFrjBbO+1FMyqMzWZdfJ1qWwYBZ9GaufDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-03T08:03:33Z"
    mac: ENC[AES256_GCM,data:vNyVJ0Q8G0KCy+5wA2iQHq9mi1VOjaNn7ht9dLP7qViiZWiqHpTP1OSyQm3iguy0/lMV2VQ9skUWl3B19ldCeXOOhqvoJmr6IDiB7hLaS4gsrMV4U6vq88KqWN0G0jh0DMAFHfrAANgsF06F3HOYBRc0UNmFxr33W9/yXiNx6EY=,iv:R3Nk0WTnYVXmtWM2Aav1o5rZC9DsYx6dfEaBM+46jGY=,tag:2qgjwW8DhA2tqSYyweYGUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
