# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: doppler-token-auth-api
stringData:
    dopplerToken: ENC[AES256_GCM,data:0qdSAnbRlxJ2jxiGuSWzdT4xKv/3Mkps2dp27T95jIfXKWhpIdxdOYTM7A0/KiXxwYIixB0=,iv:Ox1suhQgvDB1NuS79Ow4D/dcK4H6iAhzS9pP0iKxPwI=,tag:ikqVTu10PnEhnTgWn7LADQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRDZJVWhmL2hrY0s3Rm5M
            OWY1OUUycDRpOWo5ajUxQkkzSlF6eGtQT21zClFZUFBJajhhZWtLa3JXWG1wcUJM
            WWVjZUh2QXFLTHpmTTBPZ1BtZmJHNHcKLS0tIFFaeEd6S3ZHZnJHZW53cGdYRFNo
            RUxWUG1GUnZqMGU3SGMrdjNlbjJ1NFkKY91GGATjNdTp7zcfhD1L85dN9/iR2RS3
            8ukzgnUUJ9Sfl/59EtylNul3957zz2n9ipIujQaF2ky49LnL+HwBIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-14T03:29:19Z"
    mac: ENC[AES256_GCM,data:qRgOJPo48xweq0QAqcJs/PNH2+98ySK+IUjxgL075V5KjY9Ll1emrNFSpqWGWAFlKsFX0QbIrXLwlAHJCGZGp0X2EQzBevjVj0zEDpEoMJXtKc6Nm7qiDQxVLRL5FZF4WQ51PhSaLzEU9THYE8TUNJ0MznFynjDgXDLc9eQ30Dk=,iv:WX9kJCgJ8b6w35PnhlKgCRaE3nx0FYJiOf05yyRlcTA=,tag:VmCJQKkqOuyRzhw4sVLa9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
