---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  values:
    configuration:
      extraEnvVars:
        TZ: ${TIMEZONE}

      backupStorageLocation:
        - name: default
          bucket: velero
          default: true
          provider: aws
          credential:
            name: minio-credentials
            key: cloud
          config:
            region: ap-southeast-2
            s3ForcePathStyle: true
            s3Url: ${SECRET_S3_URL}
            publicUrl: ${SECRET_S3_URL}

      volumeSnapshotLocation:
        - name: aws
          provider: aws
          config:
            region: "ap-southeast-2"

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.1@sha256:a2b250d90c4baca6d2bb392775e12f3e1426940f864e0519e72f76e8f6195931
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    schedules:
      daily-backup:
        schedule: 0 6 * * *
        template:
          ttl: 168h
          excludedNamespaces:
            - rook-ceph
          storageLocation: default

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    backupsEnabled: true
    snapshotsEnabled: false

    deployNodeAgent: true

    upgradeCRDs: true
    cleanUpCRDs: true

    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
