---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.32.6
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: velero/velero
      tag: v1.9.3
    configuration:
      extraEnvVars:
        TZ: ${TIMEZONE}

      provider: aws

      backupStorageLocation:
        name: default
        bucket: velero
        default: true
        config:
          region: ap-southeast-2
          s3ForcePathStyle: true
          s3Url: ${SECRET_S3_URL}
          publicUrl: ${SECRET_S3_URL}
      resticTimeout: 4h

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    credentials:
      existingSecret: minio-credentials

    schedules:
      daily-backup:
        schedule: 0 4 * * *
        template:
          ttl: 168h
      hourly-backup:
        schedule: 0 * * * *
        template:
          ttl: 24h

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    backupsEnabled: true
    snapshotsEnabled: false

    upgradeCRDs: true
    cleanUpCRDs: true

    kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.25.4

    deployRestic: true

    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi

    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
