---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 3.1.6
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: velero/velero
      tag: v1.10.2
    configuration:
      extraEnvVars:
        TZ: ${TIMEZONE}

      provider: aws

      backupStorageLocation:
        name: default
        bucket: velero
        default: true
        config:
          region: ap-southeast-2
          s3ForcePathStyle: true
          s3Url: ${SECRET_S3_URL}
          publicUrl: ${SECRET_S3_URL}
      # resticTimeout: 4h

    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.6.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    credentials:
      existingSecret: minio-credentials

    schedules:
      daily-backup:
        schedule: 0 6 * * *
        template:
          ttl: 168h

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    backupsEnabled: true
    snapshotsEnabled: false

    deployNodeAgent: true

    upgradeCRDs: true
    cleanUpCRDs: true

    kubectl:
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.26.3

    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
