# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant
  namespace: home
spec:
  sourcePVC: home-assistant
  trigger:
    manual: my-manual-id-3
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: home-assistant-volsync-secret
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: ceph-block
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
