---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  storageClassName: minio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NAS_IP}
    path: ${SECRET_MINIO_NFS_PATH}
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: minio
  resources:
    requests:
      storage: 1Mi
