---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: home-assistant-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres database
        POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        POSTGRES_USER: "{{ .HASS_POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .HASS_POSTGRES_PASSWORD }}"
        POSTGRES_DB: home-assistant-v2

        # Home-Assistant
        TZ: Australia/Sydney
        SECRET_RECORDER_DB_URL: "postgresql://{{ .HASS_POSTGRES_USER }}:{{ .HASS_POSTGRES_PASSWORD }}@postgres-rw.databases.svc.cluster.local/home-assistant-v2"
        SECRET_INTERNAL_URL: "{{ .HASS_INTERNAL_URL }}"
        SECRET_EXTERNAL_URL: "{{ .HASS_EXTERNAL_URL }}"
        SECRET_TRUSTED_PROXIES_1: "{{ .HASS_TRUSTED_PROXIES_1 }}"
        SECRET_TRUSTED_PROXIES_2: "{{ .HASS_TRUSTED_PROXIES_2 }}"
        SECRET_PROM_TOKEN: "{{ HASS_PROM_TOKEN }}"

        # Home-Assistant Zones
        SECRET_ZONE_HOME_LATITUDE: "{{ .HASS_HOME_LATITUDE }}"
        SECRET_ZONE_HOME_LONGITUDE: "{{ .HASS_HOME_LONGITUDE }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .HASS_HOME_ELEVATION }}"
        SECRET_ZONE_OB_PARENTS_LATITUDE: "{{ .HASS_OB_PARENTS_LATITUDE }}"
        SECRET_ZONE_OB_PARENTS_LONGITUDE: "{{ .HASS_OB_PARENTS_LONGITUDE }}"

  dataFrom:
    - find:
        key: "HASS_"
