---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            enabled: false
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14
            envFrom: &envFrom
              - secretRef:
                  name: home-assistant-secrets

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.7.4
            envFrom: *envFrom
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 1000m
                memory: 2Gi
              limits:
                memory: 8Gi
            securityContext:
              privileged: true
          code:
            dependsOn: app
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.89.1
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8081"
              - /config
            envFrom:
              - secretRef:
                  name: code-server-secrets
    service:
      app:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: ${SVC_HASS_ADDR}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123

      code:
        type: ClusterIP
        controller: *app
        ports:
          http:
            port: 8081

    ingress:
      app:
        enabled: true
        className: external
        annotations:
          hajimari.io/icon: mdi:home-assistant
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_CLUSTER_DOMAIN}"
        hosts:
          - host: &host "hass.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

      code:
        enabled: true
        className: internal
        hosts:
          - host: &host "hass-code.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: code
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config

      deploy-key:
        type: secret
        name: code-server-secrets
        defaultMode: 420  # 644 (octal) in decimal
        advancedMounts:
          home-assistant:
            code:
              - path: /home/coder/.ssh/id_rsa
                subPath: GIT_DEPLOY_KEY
