---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./config-pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./secret-codeserver.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: home-assistant
