# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: home
stringData:
    POSTGRES_DB_NAME: ENC[AES256_GCM,data:HD+6Hi96PaFl9GWda1I=,iv:BD0n3oyFdFRMRjRWHw5+FogMvQD8SBuXLw/dtxHLp4A=,tag:YlbIWxwZ5t1J41QJSgLkFw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:pCebDI5nb8f7twYQ6A==,iv:la2m86lrDP6cJ5GXDUcRdroJ5/GETgahxcB3DhYbvbs=,tag:OLipYeLWQNocfoJuTvHwXA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0/gHC/bOb2JPhpleVTTDt6o=,iv:/31kVD7FKOYHM2hbK92izYZWC/dUkZYqkcBYlVmQ9Ac=,tag:2hVt+tgMY8E8OqKstW1iZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFVBWkQ4UHNhb2doQW81
            TGJoQ3E3VzEyUjI3MUxRdXVzN1FsL3dwdnpJClRlMCtDSktnYWVBeUhUU3VXZ1Z6
            VnhrTFNBNWUwbWdrWHhmbi9GaVZURDQKLS0tICs0dHBLOGoxamNiMStqY2liRUVt
            bFF0cEh6Y3Zhb2NPczM5dzROSndLYk0KS0COrHEUdMz5UtLXBJt5AWKtREwZcky7
            n/fV5xv7HbEZA6ar4JBOngOBDI4f/8wZgqn8NQRkULeHQBJ+YPj0pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-06T10:48:06Z"
    mac: ENC[AES256_GCM,data:nQUuiimi1BPpvmMTVzHrl2bZrbi6H4uDUUH9RDcsuOelJDsufPiSNEL7Xh9KAW+liUSrc411vG/GZayA5kShXl2+0C7jkzD0Jpc+5q9JwF2ItmWQsR6iXIV31yxAGUMfwgWpL9/2gx3bi331jpdYTJzdH7LrNw08VEQsvIXwafw=,iv:4g9IJwg2rVZOjcTCAVsvssyWRvbZjN0+w7uSrNX/l70=,tag:cOTBUfWAQ7F3gyQATpFIdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
