# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: hass-secrets
    namespace: home
stringData:
    hass-postgres-user: ENC[AES256_GCM,data:8WlOLhjQhnTBQBDY9A==,iv:S98UpHo0y8XJ0jCKisYbwNirPOKxpBIj6YTfyO+zLUA=,tag:bEC7jegjBN9PWVRc7pZ3yw==,type:str]
    hass-postgres-password: ENC[AES256_GCM,data:TWJQ2GfYYTm4BQHlqFzi0w==,iv:dDpMjI6jc8KodaiHly43Dx4BfjQNm1KL257aA6nhcAU=,tag:YTSlwizJBDX2Cezrks1LOw==,type:str]
    SECRET_INTERNAL_URL: ENC[AES256_GCM,data:2x5L24D0je4+HwgrZFXHFG0ylkP3Nf+VNB3evA==,iv:4hf9FTY3ekWnHdMb4nEMq6Q8nqABmzKdAe9SUBwwvic=,tag:U3USHz8IIwtlCJ221xy9iA==,type:str]
    SECRET_EXTERNAL_URL: ENC[AES256_GCM,data:TgNayWBjcpxxPJoYChkrU5QcGGeYAZwTt2xiPag=,iv:eN4dl9byVdJVxq/2TuNTceTp/xr+6PmhW84iM1ABcFE=,tag:CK0nKUBmplAykqL6pJ1rvg==,type:str]
    SECRET_TRUSTED_PROXIES_1: ENC[AES256_GCM,data:qJNZDCdc1b12t71g,iv:gqYasF2wxN9Vp2or/OWCLs0nfNI72/sHEBAXPptyxns=,tag:5UKqvZ7GpuKf2g0igudMyg==,type:str]
    TZ: ENC[AES256_GCM,data:LNX9aGjhA0Yhr/DsIJ+xiA==,iv:9Pm+a5FmGfb71p40UY0vhn+kbUjqbYqegMTUS3lo3LE=,tag:O6B33RamVGcxEEpW4069pA==,type:str]
    SECRET_HOME_LATITUDE: ENC[AES256_GCM,data:u+NXEVh6aUvFCXH/0eW/84WE,iv:GN2oIXbrN4AJGffyPGrJxH+juRCWEYYXiKoHetxW3ak=,tag:+RAhJT2MuzLLtii5Jg2j3g==,type:str]
    SECRET_HOME_LONGITUDE: ENC[AES256_GCM,data:4I7TVgFUBDjqR84k2/GD6DZT,iv:I1HeIG/q/PNSLFEKFmVGlUkpZFBhdSYe4GyleK8DSIA=,tag:JE5lvj+dwANQLiiKRqlCKg==,type:str]
    SECRET_HOME_ELEVATION: ENC[AES256_GCM,data:Xg==,iv:cxjCYn30qg1QFlvqrNRQopxQzWVuI9lbZzedJK/WzG0=,tag:Wl0zy/+Uo746aA3uLiBctQ==,type:str]
    SECRET_OB_PARENTS_LATITUDE: ENC[AES256_GCM,data:9Ro3ELpuFjl0aqU8MK2y9LQL,iv:8Y6jvx365dDTYwA8I3RB03AZnGSLNERgn/D3EKbyRro=,tag:jt4xnXcccB3YnLC6A5liDw==,type:str]
    SECRET_OB_PARENTS_LONGITUDE: ENC[AES256_GCM,data:+mdPA2Bg3+Zh/p3SSv9VawM/,iv:fxjYPs1B90nkkAfwM6vbL6XPKmo2Wu16domvLETNoKY=,tag:kTz9kXT0KE+KGUZ3AkTmtw==,type:str]
    SECRET_PROM_TOKEN: ENC[AES256_GCM,data:iD6NMpDbTUGJE30OyTPwiwU0deT5eS0oPBr+jFYngChBvg0T92kaIpKOslSn2k2ASzyu9GJl7kPEe+vW0GO0+lM8JPnKsLHIiSFe8VBiuzJ3e2ENnJXLotnaiKqjAzIWyNz4SkIcLeKSlKIf9FIiZ0bK4AbZaQnMAdKd7fL/YuJcFycmnIlB3PC/jrUMQm2jXMl8O3Inw+Mi524fML9hbu+q6t+lGFPYYYJ0sDlVkXG1lB+/F3Yx,iv:D/JDeZwtClRbZB2600kGYgyXF8oZWYufZpdtobXkBk0=,tag:WCkPUI0Rb3R+/aaP3lVT4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbFVBWkQ4UHNhb2doQW81
            TGJoQ3E3VzEyUjI3MUxRdXVzN1FsL3dwdnpJClRlMCtDSktnYWVBeUhUU3VXZ1Z6
            VnhrTFNBNWUwbWdrWHhmbi9GaVZURDQKLS0tICs0dHBLOGoxamNiMStqY2liRUVt
            bFF0cEh6Y3Zhb2NPczM5dzROSndLYk0KS0COrHEUdMz5UtLXBJt5AWKtREwZcky7
            n/fV5xv7HbEZA6ar4JBOngOBDI4f/8wZgqn8NQRkULeHQBJ+YPj0pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-23T01:21:41Z"
    mac: ENC[AES256_GCM,data:ymqI7SZtSHS6WnDCrmfc5OJusmDq0mPUgoEEYfsRGurOUpS5twN/8ppjmmi+8cPF2En3W9hsGoSSZynmDj3Kq3EWbuE8KgHO3Cx2TxSAtPSS/ZpW2J/D01C+JUA9ic0WSz0gn6tcubr/ESDPqQn9vS0uMmjwBz9G4TjRFYafBTg=,iv:xuk/w3wxhnDzOd2lkMxKiBQN+nLCdPid7prXbN4UHJw=,tag:DlQSZ9vf5J7OHF7BbrabwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
