---
originRequest:
  originServerName: "external.${SECRET_CLUSTER_DOMAIN}"

ingress:
  - hostname: "${SECRET_CLUSTER_DOMAIN}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.${SECRET_CLUSTER_DOMAIN}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
