ansible_become_pass: ENC[AES256_GCM,data:F1bvLJTcCf20,iv:04ykpeSThNL33kPDLWVjFNRXBUeeCsJFtUFinpyyNCA=,tag:OvOI0VOYPZWTxvwktWpkEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T0p0MSthOWlFNmtxNkRa
            aU1oaWh2cTNseHpXdHlTaFE3NHJYcjhJUDE0CnVqYWhJdjlta0tLZnNBUEpIY2VU
            a2hEU3ozbDRuOUx6elNXRk5NaXFPY0kKLS0tIGtqTHY2cXpqTDZYRVM0Z2M2NkN1
            YmVmanQ0a0s1VkNwSTNjWVVuWkFPTkkK1LwVj4SNviuF82rGTBIdSYXKtV9eCnet
            3EbCGxH+6ICwmQqYNvXRIq2lYLqw743mSufl4HUoolRU/fdRogoEdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T01:29:59Z"
    mac: ENC[AES256_GCM,data:3yTpsEJMckc1EYOukTlWBzBauiobkRIz6nSxhcOJe6nm0DnFy3QBbL4Rk4pxVwuEC26IQdCHYr1djuVP4b6NgoIjBlyQerqZPJMf2Yq0AoAHieiH0j4TgVSxFIMzn9YTw3epEnS2bjt0krDIwxtTqnx/HldvrwlfexLX5JbE1AU=,iv:CCz+ucw3Q0aBf2fW0LnrYx4/un4QTFCCZSLDe4xnOts=,tag:rWthxXtNzwrCEmsuhoA9aQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
