kind: ENC[AES256_GCM,data:y3IMq23g,iv:GslsRqYtdFuum5W6xr6BFfqGSr2CGoTo7GdNNJQ0RgQ=,tag:HqHmUd0bTr0KOEgvdnzOQg==,type:str]
ansible_user: ENC[AES256_GCM,data:dVl9MyO5,iv:zmxlfJ0IBSTuTF6z5Y7sWq7wKXCyZcoIcOCb9Uth/pI=,tag:IbPPbb3pCVDxyjT9h7bC3Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:4maPqsHY+TD+,iv:aDedocQkvfW2MMvWyXEZd/nLxUoI4hMvJZvJLfHthKA=,tag:Z5c0aSLVOPRh1N0iuPLE2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcm8yWW9KL3ZiNUF3dDhN
            OXFRVC9Xb1p6VDIvVTFsQkhEZXpTbUR2QUFFCldwVVBSbHova3lYOURLUDJpMnh0
            L3pMWDRjcWxOb0N6bjJjNDJ4MDRKYWcKLS0tIER2T1F1eHdMVzNWU0pRZ1BXZXBz
            bjlSYkVTelY2NGIzYVdKWmhueTJ2YXcKghCPPIocHeJXG+1PVI4G7l6ztgnBwu/j
            YRsKEniRt7D0N4ZmrV7sozvWbB7dkRhfqoSVb4h0MhrdPx8p+JpNlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T09:10:47Z"
    mac: ENC[AES256_GCM,data:Cp/R0b/4kgvj5nb5pBi8jTY0E+wSrex3gRS36fBDXzCL8unK1hPO0bDs6VE2OiusaLy51J48jn3HhFPPG/oV01mbZhFX0mvKTycNdkjLWygjSdUAtPy/9x0XzS9ZD/cFkEMKic7nZVdtLclRSMG70ta6pn9YfFoBqpT8Ixr3iG8=,iv:p9efUgyoJSR7JTZd5rBJs2/uIPJ/IW6Cu/NhHbPEgjw=,tag:y+q4Rh7dSpwP85YQ/UeQ/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
