---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./emqx.yaml
  - ./external-dns.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-at-home.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./prometheus-community.yaml
  - ./redis-operator.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./vmware-tanzu.yaml
  - ./weave-gitops.yaml
