apiVersion: v1
kind: Service
metadata:
  name: tesla-proxy
  namespace: home
spec:
  type: ExternalName
  externalName: orangepi.angryninja.cloud # eg example.example.com
  ports:
  - port: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: home
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/target: external.${SECRET_CLUSTER_DOMAIN}
spec:
  ingressClassName: external
  rules:
    - host: tesla-proxy.${SECRET_CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tesla-proxy
                port:
                  number: 8888
  tls:
  - hosts:
    - tesla-proxy.angryninja.cloud
    secretName: tls-external-service
