apiVersion: v1
kind: Service
metadata:
  name: nginx-external
  namespace: home
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - ${SECRET_ORANGEPI_IP}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/target: external.${SECRET_CLUSTER_DOMAIN}
spec:
  ingressClassName: external
  rules:
    - host: tesla-proxy.${SECRET_CLUSTER_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-external
                port:
                  number: 80
