apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Ojq8hCXPDiaaDknIxzMA/IA1EbR92jJZ2JP9ePIAQHvK0vki,iv:NBh6eDEzyaHypgq1Syt06mz8MmIaeAdbkkI7gkdyjJM=,tag:0/X+PK2zfEBXvIUgfu8hlg==,type:str]
    credentials.json: ENC[AES256_GCM,data:Hwc558Kd5TwKV/i9ZAIOzxvjwlqZC9N0FvG/eqStSzDBAomgklsT2aTLMc5u6ou1pvo09TpRvo1dkXtugr859mWiOaBcXDoyYeWp9c5yQxglYA15CQND3nftrx3tdxlCUaThb9LAzYZ2Dgdl9201S/cwDHeZTUb/pjqcUYGEt8M6OzL+5vcvo7td+AJIsGHgu0T1j2XUZTbupuUuK5GQwrYXeaHuYYwfu6yb7wh1fA==,iv:U+JTkoUS9hG0FFXeWF8TMAAjT1kaG5ahnBjSG/GbOys=,tag:m8XPp8zeJBzm8ynHm7aDGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19wgxav8atee2fr5wpwdxcex88cj9x3crhg7unggq2nyxqf2nq9rsz2hhcs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbnZEYnJXVHBZU2h0bms1
            UEhQWm9YWkxVdVQ3N28yakxpTE00SlRaZVNBCkh0dVdRZ1c4Um5LeVplMUlkcGxI
            L1BpblF0TjVSOVkxWVlxdStpeG0za1EKLS0tIEJoVHNSTEkzQWdVWnZXVW13WS94
            U0lBaHF2Q3lHUjUwVVcxRUxud2s1dUEK+vUwdcgeGp1SqVZxnFwm+Gse0/PAnJ1/
            32RxhyYEulknkXsY1u6GHHSSJDv4LE6Ze6Ay87Gi1QVEePMuPkaVag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T01:39:49Z"
    mac: ENC[AES256_GCM,data:IrXVrH23IZTXyxLUHSW/ROLmgBAJpQu8pBXUVsUwGPLbxVCoj1ILJwUcFRMlhZxPXqovAkKY0qLA+OfVwDstPzSAMO8MdXSdtbJAyhxunkSno2UI3fPBxp4JLRzLRdpqHpj/c2w3KUiTrhNXoWfZvcbQSMS3MMEWRP//D06PUJg=,iv:HpXNi3G/wDcdLB3RerUU/zfbJyOfUPxIQX7fkHD2Cjg=,tag:54nVKdqmMRah4aKr53hiDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
