apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:z2gme8Q=,iv:ZeOHW0L0gvYy6+STcEOgba+5rEm7QDL2t1f4MEvwGFk=,tag:rPZstZJMoINi3ulRMQ4gUg==,type:str]
    admin-password: ENC[AES256_GCM,data:+j7UlkxuM9P3aiJFJ2tzMvGvHMxAmQlC,iv:vD51o8ZP8XipBbSWxJuSw3n4t75wSiQzNjoQ8q7H0Kk=,tag:veg7Rd+jLTeVBEWnTMJEkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaXpuSEJ0WEhnNi9WNEYx
            LytVcFQzMkZrWG9hTk5xbjhOaXFwTkQ1elhvCkNJSWd6TGZsYzNsRGtnY1diYk1C
            eVZ2RU51a2VnSFpSeVRKMVV2RXRwRE0KLS0tIE1lRi94dTdFSWdxQXRTOStENTB1
            L29PdGV4VUp6TGZ6dEVnK3ZONFRWSVUKqADTqqYj628aIYda/JUcSjw18YparlmJ
            h3dLD3/3RIDYoMInrUwrSZGqXQo1nBHd2gvEcTOzqbsL52Yh24nKJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-13T00:10:27Z"
    mac: ENC[AES256_GCM,data:4mggxmMKufomJVdrst0QCLNO2FuRtx9VVUoDuFNS3uZnScROUkUgActaAt/Bx88ypZHnp9XWSSwsdClh/5WJ2CVlPZAw+6scUyJAMaIPzFQ1RhKrO09jSJJfFmInULQXoVW7HF0z6OmWqJ8/HKYomGwcbFc2zy4f5gnONIP1k4E=,iv:rU4+d3JzDNz82w624AGRr1J97+h/c/2Lf0r9K/h01t0=,tag:9uz4rhi4GaK6WRxtcMqdDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
