apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:h1lDcUZHP1g/KRrKMuAWW0WOFew0bNUUgbo9SIQQMfo=,iv:4sqKYC0bMUk19PEjVKug4mzsU0G0biozeRIO6vPnvxc=,tag:YOzHO45mtcfEAqJ42CcAUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWWYzWW5QeHFPZUpxSWxW
            cWt0Qks2dGw2QnRiNlp0a3c0MFIxam1ZTVRNCmJybWdDUTRmMmpYeWYvbUlaZFBU
            RnRyMkMvZUhTRThWK0xscE5EMmNzS1EKLS0tIDZnbGg2TmhQVlhlMjFlZ3ZFTHJ6
            c05BNStHWjIvdDFYNDdNM2FlcTdNK2MKcn2kC2D26uCZ3ONUOTQ5QhT4AKsICyDC
            xYmD8gQ1p10UxAevLyPg7ILD2ABsH8nfWqDr1h1KV/aZcPL/RfUSiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-08T03:34:45Z"
    mac: ENC[AES256_GCM,data:SPYse6B0ayxdu+mj+qS4DeKVo0XOlklkVOpLhMv4EASVoER4XV7Xxrw75jILTa9aE+K8qS4yss/TPL1/WPKbARndNYg/DRejZyFFKPGmqdJvgpPJkrw6cC7FmhP4+OYqorfDajZFsFpKnU4r+Zv+eELiO25gXEXsdPk6tiQ1tcQ=,iv:31pSW3nDjv4a7u3QU0k05DOPoZKVPcr3++AMb1cVWSs=,tag:uz2et5xvUjqoHT36RkySEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
