---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        adminUser: "{{ .GF_ADMIN_USER }}"
        adminPassword: "{{ .GF_ADMIN_PASS }}"
  dataFrom:
    - find:
        path: GF_

