---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
commonLabels:
  app.kubernetes.io/name: mosquitto
  app.kubernetes.io/instance: mosquitto
