---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./emqx/ks.yaml
  - ./mosquitto/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
commonLabels:
  app.kubernetes.io/name: mosquitto
  app.kubernetes.io/instance: mosquitto
# configMapGenerator:
#   - name: mosquitto-configmap
#     files:
#       - config/mosquitto.conf
# generatorOptions:
#   disableNameSuffixHash: true
