---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: cert-manager-secret
  data:
    - remoteRef:
        key: api-key
      secretKey: CLOUDFLARE_API_KEY
