apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:rOYk7OvyWjbL0I4LiPlZbyNsylZ27L83ViBX+7UYe470EsEsV6M7uw==,iv:yNhBgTax3fRTt+6+S3RcoReN8zb3kcVfaynQ10z8H14=,tag:Md96ZrNqBkfpP4iqR4Peag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZnJxMzZ5ejg4V1Q3blVr
            eHJ2aTlHT3FUUGxoVjhST1RUN3UrQThaOVdJCjRmNkRSSi8zN0NVNFROM1dHN042
            RGFuSXI1bzBGSmpsMFpvUVBHdHJUbEUKLS0tICt6bTFUOHFBNU9Wb2VXNXYweDAr
            Rm5WUWxZTVorMFRiWjkwYUVBNmRySVEK+230PCdUzL7knRjAE01GoPkDB4H9mcpG
            RVsiabw+IRwPOY37jsUGNBGJNjFXsUeUp1WklwyNKOZE+meSnH93yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T01:30:33Z"
    mac: ENC[AES256_GCM,data:3QV4Agaa5uQCm14DMsKUtpyClqf8GdTpzD8L0ouVD24mp/5hggLnLzLvBh2odhI6YUslDRtBSChvZiiAdcadimOVuILxTtrIm7Cz52mJonHwh25Yupvn0eHReAzL1TpDQk8LL+3Z8l2jAgr1E8iJ6D/eouvgoS/kTmn0HmD5KTs=,iv:C0TBQYa3ErM4t5XIGJRf9zUfOceQBTa2ahuKOEOG118=,tag:pfeUgQ3CBnAj7zmrsYxhgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
