apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:FcOGpbKCSQJALRk9eqrsrWaHhrVoCxPHt1Io0TcqKHziwYFFdg==,iv:hIPy71COA+WHLyrPkSP9J98PtOgIEFJBak5cJtzkpq8=,tag:USO572wog6r7y4DWQ2Spew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYTlUb2pLeXVhWU1JcnNO
            clBWZWF0Z2ttSE43UEJ4UWdBOXJ2aUtWbUNjClBBS0prcHVvOGxQK1JjRXVyaVlk
            NE5qdlJIYnA1RmFKbkJUcU9JMkZBelkKLS0tIGFmZXlqUG40UGxpMng2aUVLelZG
            c0VoYXpIT0E5ZFpGL1dQOHhNc3YvRHMKry5JGdaeacwstlKUGC1EQx9+72KnnN4h
            V8X1NTm4i1l9re5uhsNS5ypAQRwFbmQaqrTPUdXEIowwVjBDpNSx0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-23T08:39:43Z"
    mac: ENC[AES256_GCM,data:1zwt69vU+1K/a4SpLhHazbX5JAl6RSqqW61tYQKl0E+vGZX8NlDW7RAiSZBgyRaYrRrgGFPhpOYFeSeUPtQLqsqs6LQNTeLjlJfKDNStp11NFAXVVHkv2y+2FYgnqloiThb8eM13pkzHwZcoHPGtFXG/uVY9HmNnrC4YPUgjzH0=,iv:nGK4uZSv5gBIX1Naov5GW1r6Dr90sy4cWDzN+bab5y0=,tag:cl+CkSnTiQ2OvwM3sgaukA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
