---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secret
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: external-dns-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        email: "{{ .ADMIN_EMAIL }}"
        api-token: "{{ .CLOUDFLARE_API_TOKEN }}"
  data:
    - remoteRef:
        key: CLOUDFLARE_API_TOKEN
      secretKey: CLOUDFLARE_API_TOKEN
    - remoteRef:
        key: ADMIN_EMAIL
      secretKey: ADMIN_EMAIL