apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:bOgdM9Pqk0zTDqJ0RAuOdWms0bc=,iv:Zk/Bn4jQ9OreHnMxZr+gjXCBkVhLerq7ajyDYCcOnCc=,tag:UqUkgpTmcAAXm/jYK8wmOw==,type:str]
    api-key: ENC[AES256_GCM,data:SUt4zgIMN8kMYRiS6QMpPDAmLm/q9+IUtlDYMqWJpI14671eSw==,iv:nDFAvmTY9EeR8xMd5Iks4md6Fp7ccm30CF2+2XXLHgg=,tag:SUo1Bz0rTQXHzJRm6rJvsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cEJBeXJDdktkNlNCUkRq
            dzF6WUk0SGhmd2FaU3l4Y2FJOGZCRU5OK0F3CkF6bkV6YlQySTNLUUt5Rk1QY0Ez
            RzJ2SkFUNnVxWjU5NUR0dm9QWXpuMG8KLS0tIGFzYnFjTHROQTdQcWg0aEpKcDRD
            N1B3VVJLWUszY0EvenZJQzZ3bkEzMVUKd0JDjPn3hDEwSwsJ3OE2qIYl7sgHtu/e
            8Cm//P4skYbGDAmpJqukfDLI4or33r3B4eHHn+OiylG35mBn2cuqZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T09:10:47Z"
    mac: ENC[AES256_GCM,data:tBEDqv+F0anT3ZnO3IkQXbd2nwyDXzKnopPuyGgq75Sr+7URpehUuMwyqBPnr2aFzAMMZggk9sXTUBbHzCHdE+U2Fa21Wa7ChvwoHEOZ/dsGy5sqBk8dzi/ody58r/nOg/3kGaDPXX9JqWQprWwBdpNmUQwl5avdDLcr9eKr7uY=,iv:SVJC0ZWUvGG10jZPp4BFh2rLFVZz7ypAwNiyqcr3g+w=,tag:F0srO3poP+tYzKgkVV2Ddw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
