apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:OAhKdqzy6InWyjNIo2UTLMN9ksk=,iv:9hWNOzh34t4smxqkDVnHbvmNcpu44fwINZgpuEbnueI=,tag:aD2GZkLOIOgaVC1PC7CCSQ==,type:str]
    api-key: ENC[AES256_GCM,data:oVbydNEFw2k+0PJH8KNcoiA6NPexfeN5YIB4RjM1Ye8OA9ckNA==,iv:5gST2begD9zI6mk+TWfFeQ5n+Y5xt78e2pv0Sc+pa6A=,tag:sPQMwMcHmX6S5hS2QOTC1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M2h3S2Y3aXNrb3l3cmhz
            dGlQZndqRy9walkvZ3UyQmZMMDE5L21HK1JjCm9IZ0pVajhlQzV1eUlESTJyTWUz
            SFUxUjltL2tPK05xU05pcy90K24vQ2cKLS0tIFJ1RUtkMVBLT3h6c0tyaDcrNGdT
            UjNzK2d4MnI0Y3gzRVphOW9RYi9PemsKLhbJkgdwjtdPEVWpsPtdTAIuSJRHy+ZQ
            66taC4tJ2xCQfAuzZN84/aQEmPd18Bg8Ca4Ug03+dz5DmbBIWmWBoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T02:27:20Z"
    mac: ENC[AES256_GCM,data:Q7oyDgt5QjPiItAyn+xtzueNWe5mvp/kz9nim20dRp5oKufQekA3F4B6EBDWZudFupvGWG/QSY1lJsOe8rDcYB/16gDwToED6nmD8g6Q+rvWKI9+3VwUsfzms/fKo3laf0VN9VqBG3PT0RrSpdChm4Iarx4dooo/nqsxqWVIPWU=,iv:8dQGITeVhY1q+x9XdUIzWjAdU7QWz2wbNms50aJqChM=,tag:SRLLj3UE+twdwnjAZY5j/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
