---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app home-assistant-v2
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      home-assistant-v2:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14
            envFrom: &envFrom
              - secretRef:
                  name: home-assistant-secret

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.5.3@sha256:0498daccf881f611ca0009daf37823a6758ae80cfb523da82cb953f9ab0bc2f6
            envFrom: *envFrom
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              privileged: true
          code:
            dependsOn: app
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.89.1
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8081"
              - "/config"

    service:
      app:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: ${SVC_HASS_ADDR_V2}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123

      code:
        type: ClusterIP
        controller: app
        ports:
          http:
            port: 8081

    ingress:
      app:
        enabled: true
        className: external
        annotations:
          hajimari.io/icon: mdi:home-assistant
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "hass-new.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

      code:
        enabled: true
        className: internal
        hosts:
          - host: &host "hass-code.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: code
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
