---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: home
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path