---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./data-pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./config/mosquitto.conf
  # - name: venus-configmap
  #   files:
  #     - venus-broker.conf=./config/venus-broker.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
