---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_CLUSTER_DOMAIN/./-}-staging"
spec:
  secretName: "${SECRET_CLUSTER_DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_CLUSTER_DOMAIN}"
  dnsNames:
    - "${SECRET_CLUSTER_DOMAIN}"
    - "*.${SECRET_CLUSTER_DOMAIN}"
