# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: hass-nfs
# spec:
#   storageClassName: hass
#   capacity:
#     storage: 1Mi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     server: 10.20.0.3
#     path: /volume1/Downloads/hass-backup
#   mountOptions:
#     - nfsvers=4.1
#     - hard
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hass-nfs
#   namespace: home
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: hass
#   resources:
#     requests:
#       storage: 1Mi
# ---

---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-photo-pvc
  namespace: media
  finalizers:
    - foregroundDeletion
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      volumes:
      - name: src-vol
        persistentVolumeClaim:
          # SRC PVC
          claimName: photoprism-config
      - name: dest-vol
        persistentVolumeClaim:
          # DEST PVC
          claimName: photoprism
      containers:
      - name: alpine
        image: alpine:latest
        command: ["sh", "-c" , "apk add --update rsync && cd /root/dest; find . -delete && rsync -azPv --delete /root/src/ /root/dest && chown -R 568:568 /root/dest && ls -la /root/dest"]
        volumeMounts:
        - name: src-vol
          mountPath: /root/src
          readOnly: true
        - name: dest-vol
          mountPath: /root/dest
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 500Mi
      restartPolicy: Never
  backoffLimit: 1
