---
apiVersion: batch/v1
kind: Job
metadata:
  name: wipe-job
  namespace: network
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: main
          image: docker.io/library/alpine:latest
          command: ["/bin/sh", "-c", "cd /data; find . -delete"]
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            privileged: true
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: unifi
