---
# (string) Timezone for the servers
timezone: "Australia/Sydney"

# ssh_authorized_keys: []

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
