apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data://aVIU9eteciEFAqKIBMCXerktH0Qy0Wg0SI1xNBow1OO5XESwlXjW+mriprJLpBf887L76GRo+Mz0Qi,iv:zGZhnGRKcupIRHLEznxTwoSEg6UnJRRxoHYgQ0RboEQ=,tag:5QyUckpsZU33GWRm6xlBzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdFp0ZXh4Y0VWdDkzb3lR
            RjlQYTQvL0IraDZrc2tuZTVqUzd3YUM5QWdRCnQ4Q2hmSSsvcDB0L0N5eHh0eUE2
            WlFBVzV1OXMwUHZOTnJNeDZXZ29XOGMKLS0tIFBwRS9MTUREZ0VoMXhQOFlaTG5G
            TEtpY2M3eVJzK2NaRkU2a2tURDk4NWcKmp2e/b70Pr524Y1JyFgw37tboDRRzSWQ
            uAFOaIFsgOfqlIEtqlHMZ2HwwNW4iGj6esPad4A3s68slKbs8bDdeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T09:10:47Z"
    mac: ENC[AES256_GCM,data:iXj2hZeArXzv/clf/3ESwm7jMQUbA9ZbPKRI90cd/OexIYXTu7kA3h4VyT48tsNF2dy9uCesUacnSsDhfD7C7WRyKwve8rhRUAmtKhGYOIj5lDk2OdzPB8xtuyzLmr5Yyqqss7FvOeU2Hk/lPQLTeLXvUuhZJd6odzVEleYfk7Q=,iv:WsbneAYP8HsEmUwHIU6/LjInTMHdr5RqH7taDTIpP3k=,tag:agYMPmsrZExEnKdL0eY9kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
