apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:J7+bW7xaIaa2jz0D01veDg==,iv:FbAt6HPTGllcBIg2LrD5HAwCB2Lm4AmRQPfJygXEjpk=,tag:vqvaJz8ryjKUCjZP0WuxuA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:TMiANqJ7uESlJUiGO5kHAbaxWV0=,iv:yN0XNUn3S+bVatNwtgXJ3XCTnVSbE3ep2I2nSzpPnH8=,tag:qbkRW2ud8zy75/TTmsNrgw==,type:str]
    SECRET_NAME: ENC[AES256_GCM,data:WE64sk5lgjl4,iv:FqyU76X0Rwh0iD8K319qCfzpvG2Mu6NPUzV4pdW/YoM=,tag:BybDRBdjpiEnMoMGFyFazQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SvqZoL1vXXKd6cbUHgHvfrCtNZk=,iv:SOAMIYGylZYsv7CDfJoNh4c0/bFrCfiSb3ClfyTCR7o=,tag:9/EKr0XeamvHGVWTmBb4+Q==,type:str]
    SECRET_FRIGATE_NFS_PATH: ENC[AES256_GCM,data:hwQC6HJvFZe7zwD0efP59JhmmeVeqw==,iv:vjRAiLfd/H4XvFikYtrFf6w7SoN6HP6Xj1nU+tOm0CQ=,tag:TFoyu3HAh3lW40nqVv/vvA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:hj6YuO5sZZjT,iv:a/JGjRlvH5fXKOAgVb2ewIrjAe6g8WZlJ9MLWuZ90ho=,tag:Mb4jGcSibH+5T3PkEUnupw==,type:str]
    SECRET_HASS_PROM_TOKEN: ENC[AES256_GCM,data:XiSNHh47JUFiwfMfBo6SHwUcE1E7FS1Sv5nvvGKmWwF2sMT5zP7jiY9boqcJXRqYt1QGn+XUAX1R/CGNqagYJ3OZFAZ9xF4fi7S/tlb6R/wlPc1tgoZpEWtL6orQ9U+iSYTydAWiOieugiWmgWP2/3lPLPapar9GHqDmFFYoJqREnTwRqCK/TQpsEVDzTkVuJu8/4+kAidjGWUetO6Z4razz5OB6/ZP+azKTbpH0qSUhebTCJKLB,iv:smL/ZemdGLJXqsbRTiI2+e4iwDwvHBj2itdkd3GVPdA=,tag:+FQDUSCVVXXbmAGy39G9AA==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:ARl1qOs4l3frm2SAwj7tAHfxfB4=,iv:jO0jOinxinIFGHlFgqEvRvriD8TnXyS5K0JsnGgla6U=,tag:24jmKg6Acvn2rznLUr9mdQ==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:tNtEphqqXtnSMTOpkgfTE8y6nUdyDDpPu8X6EAZr80j7z5eUNDW4gA==,iv:/nJ78Q/+Xdffobe6buECITyAo8sr6GWkIZ5oDiU5tj0=,tag:m7KYwc1X8kQajZJRh3XD+Q==,type:str]
    SECRET_MQTT_USER: ENC[AES256_GCM,data:P6fz9Q==,iv:Ja51y2welqLEcaWNMWn3BqaCt7WyXixRCCnZCsB1dYA=,tag:LUkfNkgq/ifvczpJ53hbCw==,type:str]
    SECRET_MQTT_USER_PASSWORD: ENC[AES256_GCM,data:8K6MRFRqTzwlDA==,iv:a6UbAeBN1LnM6cEPIC7ksXQSD4elrNHtl5VPggUHX/c=,tag:7AEeFkRuycRYJIS340jRcA==,type:str]
    SECRET_NAS_IP: ENC[AES256_GCM,data:BLHXKTr0FrQ1,iv:0tp+IDgZUlKA9zSBVw2FfYhfjNax80aF2mBHVvxkaTY=,tag:eTsVBD7A5b+JUkrFY+5RkQ==,type:str]
    SECRET_S3_URL: ENC[AES256_GCM,data:o6UU0Si2w60zaPDBFzVwz1Cmj0Eo,iv:XtDt921uEQE5HELhvuHoPMDxWznzve0q+ExfmVr/c/Q=,tag:Zy/nWW7CtcrCs5451gtMaw==,type:str]
    SECRET_SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:L8Hcb0gtNhkA8NWREblBgo1oTyKfUNwANsALOvhOFMYb9SVqkiSiaqJyphawHGSSNbEpsZdQBCyANeEICyTWzxRpz45EypZ+z8YpQE647OC9,iv:A8m41nBIvbeAV1OkoVomIPD/Hddb/B3Q2+ks5MZx+B8=,tag:3BMTe9pk+GOFxvsT6BUfKw==,type:str]
    SECRET_VELERO_BUCKET_NAME: ENC[AES256_GCM,data:3emD9Lvg,iv:njbgwcMCTzFDULIDKITdkEHLacQhxNVwKXKvVE2SO4M=,tag:x+jvYWekdY8dYFKYrOzW7g==,type:str]
    SECRET_VELERO_BUCKET_REGION: ENC[AES256_GCM,data:wAD9VfQ6Vu4Di8l0PJA=,iv:/c/ZMyhTbKhcZkGBd5mN25wc+VmmIYMWwwtHsez2s4g=,tag:nvEXIhPtSeruS6foAJFwuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bFZ1aUFLM0srOVNXNEw3
            Wmljc3BSVDJ4cnJVbzE2WFgxbEJyRWk5OEF3Ck5LY3EzMGZuSXZsYzFuZnNqeWRF
            SUNscVJtOTYrNmJDWVFXMzVoalluckkKLS0tIFMySTI3ZDg2Z1JVY1VFUjRkMDJk
            R0lIeTR1OGtYMmtzZ3lYK0ZENnZLMGcK2s3L6IQGcDD7oTp8sFYPGhQl67J9twcm
            sTifxaVRs1ugC504aFReBRk03txX0y/qgdUrSEG6GfnU883/RRwA/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T09:36:28Z"
    mac: ENC[AES256_GCM,data:CBbzPt7PDvXDB8vLd6OAyXzrzjpFhu1DZXtTJQk78O90G7mwWGdQTyr/ZC5ESB9NYvO3d7l62lut9dRDgM6UosVXQbM3tNy7t4WhZZoDy/KSsxrD5uSeEBfEnCxqhdV/CVqZW7BHNtPrGG9wdYArW2PxAEISqLuC/Rfc1ig1EaM=,iv:hkmorOVU1kL348mHFyXevdvx2a2t0d0itG5K3lPFWxg=,tag:L+GT9GA/pt8hzV+Jq72LUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
