apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Unhl4QYjcpCZHSHv,iv:uFXVqKRPutfOgQSsldrK5BHTa5/a/uPz58dKPcGk8jY=,tag:58jNi8xuQdxIxOvp4QXhdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dnV3UzhhZW5XbDJSR3pp
            TnlWS3VVL09QMDNvdWQwMFdvNGExS2QyTTJnCmo5WFJmQTRhNFlYQ29OU29YcGdp
            LytXaVJqQitHdjNmSTZGNkFUQlZ3T2sKLS0tIHRYV2VEb3pPSmhRNVNtbWpDcXdH
            QlZub0xxb0NrY3FyWEcyS3o1THlhcmsKR7egF8EZXTckAqoLAeATyAmAnM2iWHFO
            IU7FMtzYq93EQ7b/O6INDptHWT1WfoifZFBdOlkLJITbgOYhudLmfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T01:30:32Z"
    mac: ENC[AES256_GCM,data:bWf7GFqB4xhDdxHIoIhH8n4Fa87ecEzpl12lFCA1rCr/QFs7C+0fn96ubV1++Aq6Ihq6SKogxzR8j4qny9/ASGMykRYZcH5bMBJvU/ViFQ3jte0ewGKiGrvEeYaCdJsvgVBOhtPxAowMyN7HE9dmOxQjBUxMi79JC41ODQMjIF4=,iv:xhZvzHirNgdxT2j+7oPdg0nny2T6f1SWFwsBbmW6jmE=,tag:9xnI0iNp0pETGdjRIch4bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
