apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sWJfLR5nI3wK207xLjkxxXiSzyo=,iv:kvV4oMfd9C9yqUgsBHLlUXCVT301jE8HRXx0gB/UbsA=,tag:X8yhcxuq+U3JDG/k2WAxeg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:e+P7R2o8KTRrbodtpYR4uY/kb1Ugz3hhr/iVSTQMrNXS3Ik/,iv:qrUufGWLGttt145Pc4onqzurtI0Oybjp53cHudegCS0=,tag:kCuOCoz+Lh9KeEegPVRvvQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:GYWMKddzFthG411Tzty72g==,iv:Pp85D2aCQ3rDl+P6r0+eJBvkAFwylgmV9h9wosYvAPc=,tag:qKNiFIH6lKlsEdKKb//qBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RnZKaWxqS2xGcjVJcnd4
            a3NhVTh1eUxiY01HRDI5ZjFyeHBOaFRPeUFzCmFST1Zpa0JPbFJBQjFFZTJTUTI3
            bkFtNFhnQnI5dWJIa3R5YUhzbjJ0RjgKLS0tIEgyTDhMbW4xV0hYQUtKdkdFSWQx
            TE1IbUNLYTA0UTJmTUtnVHhKUDY2TncKqLL+XKi4PAMDm18G8P5doIrq5DoCBJz0
            eeJqSUBnHhrbTpocZ6YGI0IWi3ooIesAEMINlpSozSL60I4fjKzLAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T09:32:43Z"
    mac: ENC[AES256_GCM,data:Cap7qRInX3hOAz59uGqNqzBb2OftKZ6RXre7c1Km87ms11PDpcf9QqoIH25HwcldiU/pQESkK3HVE4ZhUjdXkN/an/q1BGgnq1r5qgcrCuWl44O3FRsn6jR1mP6bsUVK13zZHAGGFD1g7WkLMQj+Ohf4UzGtYZgnW8opYSAEOu8=,iv:fJF1IVCGAfbJIieGgxx1oqyFKxUvkhIRB79XbOqqpCU=,tag:CPSUnfOVrS1+0nKcvth/Sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
