---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Sydney"
  BGP_ADVERTISED_CIDR: "172.16.0.0/24"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_VIP_ADDR: "10.20.0.254"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "10.20.0.0/24"
  SVC_POSTGRES_ADDR: "172.16.0.9"
  SVC_EMQX_ADDR: "172.16.0.3"
  SVC_MOSQUITTO_ADDR: "172.16.0.4"
  SVC_UNIFI_ADDR: "172.16.0.6"
  SVC_HASS_ADDR: "172.16.0.7"
  SVC_JELLYFIN_ADDR: "172.16.0.8"
  # SVC_TAILSCALE_ADDR: "172.16.0.8"
