---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Sydney"
  KUBE_VIP_ADDR: "10.20.0.253"
  METALLB_LB_RANGE: "10.20.0.40-10.20.0.49"
  METALLB_K8S_GATEWAY_ADDR: "10.20.0.40"
  METALLB_INGRESS_ADDR: "10.20.0.41"
  SVC_POSTGRES_ADDR: "10.20.0.42"
