apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qsAvEqoRYracGw/Mmnr/zA==,iv:m8un7U0a/uU6vjC+FGcDewtn8qykZA7LUhpmHJMF65g=,tag:enKpTnnSiA+Ogt+zI4eTiA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YOGbwbmm5zHhSsyCHWz4GxjvO3M=,iv:Y8T6YzN5FEmZQthfZ/UJB5P+cqalqXFNdHFv25wCjDE=,tag:1E9R0tTSuzBiYSfKNHXxFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpanAvSTBxRlZNczNJSFNV
            RDc5cEN3V0ZGMys5S3JjNHVyQzVIY3BiajFZCjVFMWZhQkMrMFZKWDNoZklpV2dX
            bUNNZGJmc0ZKcmtwcy83YXdtSERrZ3MKLS0tIDhvdUQ0aHZVRFp6TjF3QzJLZS9L
            azBpM0lESTd4Q28yNVNpQ3FnS0ZpZlUKshOlYVtv91eOl15cHrgp+T7kFvTfHZIU
            9CwLR0ll3B2jZIVlbjPzZHkMIzQjhp2QTyjRUPIBvf1U8nkLS1a9DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T02:27:20Z"
    mac: ENC[AES256_GCM,data:8l8sFFHZHfkAHbA3lfBQO0JZwAfFCzvT6vpKlCaMQv+g8jiJUcuDKh6o3Kx6L4erE41DOCCbfBrMvHDCbvI8SJ/JwfC0iz9+WiAdbgN3I75l6lGR1mE6xPBNfhOjRJ1Ma+gOfiJOmeaB2V4h0ZMEik5iySjg/BKPfLX8FvDVrPw=,iv:MJlP7f1UyC1zEiDqvjia4XLOEcRJKv9bKwTDPxiCFMQ=,tag:YAIRTSG6pxl9UFP4AU9YvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
