---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Sydney"
  METALLB_LB_RANGE: "10.20.0.50-10.20.0.59"
  METALLB_K8S_GATEWAY_ADDR: "10.20.0.50"
  METALLB_INGRESS_ADDR: "10.20.0.51"
