# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: photoprism
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      photoprism:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: photoprism/photoprism
              tag: '240915'
            env:
              TZ: "${TIMEZONE}"
              PHOTOPRISM_SITE_URL: https://photos.${SECRET_CLUSTER_DOMAIN}/
              PHOTOPRISM_SITE_TITLE: Home Photos
              PHOTOPRISM_SITE_AUTHOR: Jon
              PHOTOPRISM_ORIGINALS_PATH: /photoprism/media/
              PHOTOPRISM_STORAGE_PATH: /photoprism/storage/
              PHOTOPRISM_IMPORT_PATH: /photoprism/unsorted/
            envFrom:
              - secretRef:
                  name: photoprism-secrets
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: photoprism
        ports:
          http:
            port: 80
    ingress:
      app:
        className: internal
        hosts:
          - host: "photos.${SECRET_CLUSTER_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: photoprism-config
      media:
        enabled: true
        existingClaim: media-nfs-photos
      unsorted:
        enabled: true
        existingClaim: media-nfs-photos-unsorted
