---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
  - ./nfs-config.yaml
  - ./nfs-photos-unsorted.yaml
  - ./nfs-photos.yaml
  - ./secrets.sops.yaml
labels:
  - pairs:
      app.kubernetes.io/name: photoprism
      app.kubernetes.io/instance: photoprism
