---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-photos
spec:
  storageClassName: media-nfs-photos
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.20.0.3
    path: /volume1/Media/Photos
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-photos
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs-photos
  resources:
    requests:
      storage: 1Mi
