# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:iH5BWdQxhZkJ,iv:b9Kt4FpkWlukEgXjn3YUpxRfPJuT/gYXqnjYBBNyymA=,tag:Jf0VMc4EhaSThPlpRnfZtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TnZCRlZGWGpJRHVWK3NU
            OEROeDFqWW1MTDRLajZoZDJGd3NWRDVSd1dNCnByK3pWTmFlbEVObmx4YXNuSFZl
            UHpRV05kUmdVYURZakpSZEwxSVFWWjQKLS0tIDJMcWNTcjdwY1ZNZ2lsUkkvWXBQ
            Y29wZEpJWUJsR2FSVkluNDlueHlmejAK5B9btLvdS4zl155zxOd7CWyFkwX/UQ8m
            Ll5FAhb4qoBCN50Kr4fA3uFdD1mHFpUWAoimYUnwQDvgbtt8Iif3NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T02:51:25Z"
    mac: ENC[AES256_GCM,data:KML1equ9c1mUpkQSjryyKO+1eVMrt4xWkSbEhEWbDvVKUMpGkZlA/4UCBsv9vMesDNfj2wKt9YduUOs8FiGWSG0TnYYZj8SZoZrlwGcRxGbQHOts5fRMmR3xlmlcUTrlfBy3kKpJZE/JKmRpZCpSdb4jptXXCKsOhPpdCMSDu+U=,iv:rRWPnh9haNVu2YkTAGxE8js3wl1F91ROb0b60qppaUc=,tag:DiMMsEqIhGYdRN0txQuOlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
