---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app frigate
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cluster-apps-external-secrets
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-intel-device-plugin-gpu
    - name: cluster-apps-local-path-provisioner
    - name: cluster-apps-mosquitto
  path: ./kubernetes/apps/home/frigate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: frigate
      namespace: home
  interval: 15m
  retryInterval: 1m
  timeout: 5m