---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: minio-secrets
  data:
    - remoteRef:
        key: MINIO_ROOT_USER
      secretKey: MINIO_ROOT_USER
    - remoteRef:
        key: MINIO_ROOT_PASSWORD
      secretKey: MINIO_ROOT_PASSWORD
    - remoteRef:
        key: MINIO_PROMETHEUS_TOKEN
      secretKey: MINIO_PROMETHEUS_TOKEN
