---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./release.yaml
labels:
  - pairs:
      app.kubernetes.io/name: speedtest
      app.kubernetes.io/instance: speedtest
