---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: monitoring
  labels:
    app: speedtest
spec:
  selector:
    matchLabels:
      app: speedtest
  replicas: 1
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
        - name: speedtest
          image: ghcr.io/danopstech/speedtest_exporter
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: monitoring
  labels:
    name: speedtest
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: speedtest
