---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secret-v1
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: thanos-secret-v1
  data:
    - remoteRef:
        key: MINIO_ACCESS_KEY
      secretKey: MINIO_ACCESS_KEY
    - remoteRef:
        key: MINIO_SECRET_KEY
      secretKey: MINIO_SECRET_KEY
