# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:BXTBy2s4cfdvgyW7UxFekZ9MuW1mbdCtAruFqRXP4i+a/QODli3YlJSupqH0NKJuQqpqQyC9OrZWjgVj/Sgiow2UqLUN6ZxIzfizYKaSGRnUb0yPqDI1eMRFHix2zntaN3DIP2LdkceuJ6IyE6cB2gIFySujMyBZU5g0KdQvPj1uHgxZVAEkuGVfmeFkN73V95zs5OAEzbkzJajT8MP8,iv:0rdyk7E+prwtwxhg2pSHvvBn7NjO5ISSPDrXBD0dRdo=,tag:uroqjYBZSaDZAwRMptvRcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T11:01:09Z"
    mac: ENC[AES256_GCM,data:y3+7ilMJOxnarkrWzdtzslyQc33kcwgleQ+m+EC+zq8zvDuTfReYYfsGUJOqNzklsi/OpPFlEjtvoRN9Uv/sFZdaFz8dTQR8TCFWlp0pL6A9WupdiUzFNuJhkTeA2VDdQPbw/uaJoHXBUHDBWhPGxWNnKtPfVeNIpn9G6AXn9oI=,iv:oZ78t21u3Rh9Vz6HLTWKFzBJ/pxtgv5W3Yw/PG85SIo=,tag:BnsZfQDLco1FyVF2yncKaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
