# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:YPIx9ZL30QoypHB3/J9X8+/D5/XcgL+E3cA5iYCKQ2TgwT3VdewnOXzskwVSjpx5+tAK0dghnmq9xFGdS29Zayhz3VEJS/sXUUhLkQ5Y7fGlNgbZ+KlcJIUl7ebHOvRiekg3NY624qRjf/+NBTG/nAfD+ZqYw6gZXs0/Cncz+IBtkfs0oMx2QB3zdPGo4pyciBYk4C41nwUvkXKWMVutVa9/36BgoupxRO0/ZBSbL9XpmQ==,iv:GCYdrXvnYp0nJ0nHJ93m38qmc2qD0h6zBB5FeucvUgA=,tag:RsG7JWHjmQdgpbawoNcPdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T09:38:10Z"
    mac: ENC[AES256_GCM,data:xMGbURRIZU59K2fFO+OzVh+b5re7zfZMRQiXVwjJRNjfOvnjbCwkIw62kau+Qf3O6+ThG0esLthS2ya5XM/sOrwSdbI6jqF9meCrhXXRYgISrKoYvaF0h7JDrr67r8LSynU5330AbYbCOX5r0iZjU87nUNQSUP5jIJP2/+rAELQ=,iv:S0sRLt3iuoj51BW9yo4+JOpFebyl+5++ggsAjgltupw=,tag:paPRKSGTiJITnVCBVX+wwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
