# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:Ue3YmLzlWdBzlUpNstKFNydiJI9CwEl3bDhcu7batJ5TuQDpSOgw+YoWg+WOKup3YLR7ZnYjcHJMfkaeEX4hbi/TTcKuXFLJ2Of5n/TVjX21Xky1HO0JXpbpAwuMpI9m6W1m9ALPmBNdpbVwJHHFet7Ej9XVUE/QqDDlQgj7LHV/xyIY5IrPl0FSopZKdYQcfRfiPjR5FVhYx0EaznyX,iv:fBM+I1i+NSnVOJhlUOI6+HhSrK0/m9JQjgZkGM7Bh6k=,tag:JNyhMZFJyaPahvjDj9Z3hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T10:26:07Z"
    mac: ENC[AES256_GCM,data:oY3zvs0qiqaWxxnY0fzmMoyerY1gW8jFfUopxO8SuzfoWBuNWsYPdYpANolEGuTeLLv6pOxgpopyJ1tT9MzSvZxcIogYAC6naZ3Sy24apnwoL3wWeo1kolFCa3PJdIj2bWiyV08eFZOCEY6NMZSIrFCDWmdnfG/UXmLDwkyEejs=,iv:6TnRmAJ6W4AeaVor2Ueyy8pprXKRDQDnqg4sLDSVq8s=,tag:dkv4ZwzKBpWkoZ+jPy1LZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
