apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:HceBEImkPFEjc049mnFZGQ==,iv:LeOFyX4+b/ANr9SdHUpp7ro/SETbBATaKaCz2pAcD7o=,tag:lfOJSmfmLt8HG5zeLb9Dig==,type:str]
    MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Sao/VYdC4lTtXq5JIAhJUlJsKFdxi1A8Huj3r2GkL5s=,iv:tE7dxTc+FPxyKRGv8FP9Gec9lYuDs2ZAjXTv5MF5xZc=,tag:wJl9H/tJ6YPFrEIkGUgY1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-01T06:07:39Z"
    mac: ENC[AES256_GCM,data:zQYTXJ4SlioHUXuIvErr31hnqQEAI2C1dVL1cXdN/yovy6GahQPVHtawuOdruM2vMF/Su5sL4xSolO80yraOk7LPlGS+FIZsPYnY15ap8RQQSCeCGy6jhaJDSpcmpf8KCXYLuZWJiu2FeZPLxRbWQSYA13MJLGoHJyXScYmRtok=,iv:HIAF6NSe0p3zhs8W353+9gNQN92llv8J04HW6BWowZs=,tag:v3B2DkZ9j1PkmqWDw+Iieg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
