# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:kt2Uevxt0d4kdnbptCodcqS8zMgngLIXiXiX/XCh5Ovj+iMUEfsOqZlIqjuNNSrZg2z6AbLCbiwhYerp3TqloMjns3fIUXJHYYZLlTem+mxt2xVRuFdcNHJHEX4lQVzyIT6yyWw3hpNBHvxQDy1SavfqSyMyfWAUK3sJrKRTZpCQPYZcgtyC72IXwSEuVscty0bWjvOSn/GLQndnzGPOI6j0uAoFbhQ=,iv:bqOelLczRqeJlwax+FPPekbHpvyj8RBuDoArRJRqVAE=,tag:BAYfvFw7VYv45nlu5fwvhA==,type:str]
    #ENC[AES256_GCM,data:T28SF2tYQOSnj1dfEquwlaTx15VnGefxamc5Eflu+NBeetiP1gmAhrxQCSeiR/y9SeIY3b4TwKLAZ9i19/OA3qT4Sz9uwQAoVIjAjpcRflc6D9f05YavO8ZL4y0IPZjf/e7n2mNG65v3sFQshPePZUqc9qpPFno9LVriDerTSC06rVG4ZaWBn3VhXzmO5ga+jYWMLkMr5O34Sk7JAmuLaw9Vlzqm9Kqqpbu8jJTeF+23y6ksk+o=,iv:ZUnAYhr/iidHLGvaBRg01prqrDJv5giiwVSfgAddC4g=,tag:vj7CuC4zZz/FymtPaIsoNA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T10:24:17Z"
    mac: ENC[AES256_GCM,data:p1LiPKuiMTN5x//H+E2WTMdRGolq+lJPrk5M5O5RlaG1fkk/CzsrkNXcDts3WXDmNEcbYTd8+5edA1YH7PqjriLUc3a3hI7+slJitdWVK6tvw9KWOQvyuhKgNKyRBhqx2xS5qVQTNushYBz1V88BW47d8c+v7OG2KXZnkf7ydf8=,iv:vjRm/3KylALaoS/XqahxsjJ060oOL5CXlc/ZEdfJ9jI=,tag:/fKW8rPMnDHXM5lqpS5kVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
