# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:L9YCTs0pWnBuBIDT3solEGQ4/XhX+m94OWfy7A7AEWScFfcy5rjzlV3NXtcTC1Obwm5XdeyOxbrIc5ti8G/C5ji7b1vVScLndM2b3Ig5jFL5wkxLyV7/KEcr1ioJL127M//l782MGf3Jgl84eSSlEGefJoWzmwTB6xruZNpTTfi9IZkZBfjvjMxr0QRNRqCC09ViYTNywA0HUawJ,iv:xsuU+wWrpeRVP2YGdEXDnYDD1VdDR6tln4PVYgBNjTU=,tag:Os81TSS2DsRcXm0fNN8Nog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-19T09:04:09Z"
    mac: ENC[AES256_GCM,data:g2fcqdEU+/cHoDgsGO36mql5aIMcKZe/Hb68Ok51A0te//mI0FGppfK0iAgofBvrpP705QnlQY8uPxOiZ1kfjeG9maZ4ROW2nfxzHd9VQRiwU/Yxxl1gPM8Ppnqnl/eeWDTTkBymgnjVJDLmJs+80HsZ0XTyBT89YIw5EKdtKlM=,iv:fvEHaAnTwViHL66ink13Sd0O34LsGE0sr1a//qvX1ls=,tag:Z9Uu7B8bva9IsyKvhkH23g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
