# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:XpyyT66ltUnDbZzB7HaETThit/gwW68T0qvhS5vPj4eCYsSyrmUfYKZQAQ2L8dL+9Z5GwdoKmKqb6omBhDzWqfnARx7pnlJA82VZaWmj6abK+nxPhsviq/Iq2pDr4bZossBQjtBRzI1znRjwW+yLqhqPWUJMMR1OUnj+z81O3a8iSycSrQMqj85hdDwqTuMXXPrAasGpfzPafP8bG5UCVBZbv1+82/Qoe8hVXlmh9qvdJcwWm8u36oRDkc9qYQ==,iv:+NM5C2UNaTg4Wlmy8A9Ao2IwI+KUwT4iAHEjurIHNRk=,tag:qdF5GgcUPc08dxjEVW8wCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T11:25:39Z"
    mac: ENC[AES256_GCM,data:u0nx0BmfAcBoZO1ZaRwJO6abe/MEl0LlmMDENbnTo91W6FdQbIy6dgrajSc3+otrM1n4SLjETJSFn1f6YZ+dnc3QKcwS3VPamDtNMD3v7wPIUfsK/oK0mtjZk3UddL2Nx4hl/FVGdC2+inkMDWe/Bl7hXrYOLMJqCbiyJp+QpWQ=,iv:mELBHH9qRfW7hI3jCmn3iigUl85vnQQk6qr0xtncYUQ=,tag:A8j9Mdg34EqP0+JRyzxtKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
