# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:F4nhOKZ4z9GSQ5zlBhQl1u+ca4QgrgHb3xbPdC9za4nBwhrG8OdexXtd55B53AGPd2f1kbNN4HmcXwtHG36E9to+hP9iMvTQAZnXsnKyGKEK4K6yM/Cln4IXfmW8sJohwcKTQEwng4g3/gTfeGtWJK+8N908O7sDj8+5WDRpEBdKH+N+gxBConvLRyjqtDzWxSomYqJ0muR9MTFlAMxpZC204UvBGfAqerHSnqajuhh07NQSIg==,iv:okpiCq4uCWI4Cvq6GUDUmqFkG7HKMmNORXLikXJB++8=,tag:DBzrxHR6WBm1pIhe9MY4BQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T06:51:29Z"
    mac: ENC[AES256_GCM,data:2uWPpVPBmRU71fEpNU4y4+7tTcg81KkEl1iHfQwH/c5s24y+aesqHawyBwGQETovwoWcmooFW8aSxGZN50Wozg4BN83+omqhUnNF5WDeOpHA08Q6kizKiY4q4EH28pfvDEIDezYHJ8d5qZtup6kqfUckR2vqmqq0pWhh4Pzcgk4=,iv:KcfnJvWI7WZ3/CicjSDtxiZrEasmQ5gsEa0jAntApSo=,tag:DNalxHQ1zskoRMu2R/UEGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
