# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:OA1FHi9NtzKBYM78V9Sq+DlOxR4DOIkz759haZiULN1iF8DTlhRb6M17DRcFjexlrOcB939dO5EBhiPbB1aTNG+9I1dD5MqRqzwPa2dvV25JAimkiKSFHPyMlYPSvYwxXTlqt72uS+oKpZPDrRdBiVrwW/QNI8hN/NXR3OJ5xAwNOK/CKkPO3Zu8A+1z7jt3mfDFf58eQR31+1xwm1Lb8zZIU+tJjFXr1AoqDL14dQGIgw==,iv:8Gtg4isf2EK0Adw/gu08N6MzQzeWz6jYH+xYg0ucMtQ=,tag:WvdZCx/aDw8U2tXNVwwmdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T07:29:01Z"
    mac: ENC[AES256_GCM,data:efuk7aaiEcnVhmKyMrap6elpvfXpvzucUEnT8+o6w1M3QY1vzrX1UnSEpZigUmaHJyj3tAGNQJtjWAIwvC7IPuasgHI57BTQmk60I6tLSC5tKDz8QobU5Id37o1x80vZdAtQC6/Zz7tLVlU7lxJs9rdQqRbAFESH+tZRXKkyz5c=,iv:LqNcKhfcxapm+gKOp+2OcnKGxhjOZpPER84poa1kuUk=,tag:XzIiisqLS47iNuCvmV6yVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
