# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:DbjW++lfV65Pwna+pRs8x3Z7UgWIFbYP6vU5et+VVqezq1g5xbOCVgvTP7Vy4t6aRre7A2GDvce5RTERCvwQ9BV9GXtGYl35wbT7ndmP4YBxd73bps0mbMCs6XR9FI11SA5oNNRU4LgSHLxCBWosecuiUUHqxGA9dTv6fxRtUXSaHVsDXQAHAkYrCY50qImA/f9nX/ro2GpQigWU,iv:0W1LSjOOc+dlVXG4FqtA5IRdi4MJxZHODglqdZ/fqT4=,tag:HPzFwcmYDNaBiJ21cYzNWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T12:49:15Z"
    mac: ENC[AES256_GCM,data:pjFaIjkz1+SPXnvi/Yci6XVOFxyt+orUcHvre3ThFRjSRQJEXLjA7nD5jQh1ga88OcM5/R94SVwXyV5axqP76gnR8+V2876WBmAtVJeNQBrOgzs9WGuyHY5RyeZni5JWH8Zu3pXT/z7SGWp1/XoM8lTnG+oFfnaHSxD8N7l5WEQ=,iv:IcoFehE1Ld7YivwZjTJDVWnjzi/qjaZCHWpYNkirQhQ=,tag:lzXXbtc6PJ88YexbBTchcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
