# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:wpAT/66FpPWsKW2tPHX+0xsrdQ6lRwh4PcXFTPIDylVKEy4lhA1lPDQHVmcOV3EK6GB7VJcwn2VdfG//kvr96a1dOSN7DQYvR4qXpD7hM1N6MansSRRVKfkuephEC+fCpDpzu9pexpQcOcPp67kp+jEQ4yJPbnvEQi7m9EdQIedXIrVCELPr06Hd9fbvYYlOpPZqVmScAYLBEY/hUc4M942XlAdyxxP8s4XTl5qAMclfEQ==,iv:DqcE1E6ivtIfn8bu72cxTdIUdi67EwfuJw17qvzWe+8=,tag:7SS9yhfVclTTlQlXPu8zXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T12:47:30Z"
    mac: ENC[AES256_GCM,data:jGd0Xa5jl2nxoCgLY73SdL6noIXuLOxcrCV4K1Yl/1ZarkKklUfEN78e7izR7ntv5jt5wbo8APubEGC3h21dhPO/E3Zt5Jv5vFX9QtiTqwuxSPg8CB9Ark6NcRQ0XWQVcKGhG5QIyN4ayKujihrHQFn7Z8GKV3oTWeaC++YXhNg=,iv:HA8poB/lm91JZVoK15g/gHQVTyg+IFfqiCddeUGJ0po=,tag:bZqK9Mpu3BtYOQPMKZQgEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
