# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:/BCM6ftdy4k5RvuXdoOnATA0vfJW38wF+H5+JBSzEzVw43OgAx1pCuC0G5ZJ4EA9TXEZnORCBEP76SkyWfubh+cd8I9dkowE6k4uKSyiSkiN0cvuY/mhPi1fJqyN/vV9AMhLJYE1TKiXf7PQBnijAknsLa7BXNGmT2Db/UQWxIlrZUaQps8EE0kLHjgO/f2eV4IQhHK1AXxQbP2rM7b9a3Qkl4D1JvrXo0XTHonhXl9jbQ==,iv:dhhqfZfSBACzf3sBI9haPX5AbMrkb4SohqUU26Sdr6A=,tag:fnS1/cELesP0NObu7sGW1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-26T06:51:49Z"
    mac: ENC[AES256_GCM,data:gpX5RQ6JWyifLT8baI2oUBuM7TqLQV2+qUREEXs5hUYVKxXmvXVt9y/S3jCojx19WFYv3PUwdt6newbOkKLiP5TvRTAiGRYSEnSku3pMVL6JSFosjBS19WZfGmxFQhr33khJgCRmBUs7LCCT3LaWKbHXGndklIwDNitKj0Blgbk=,iv:pFe8qaxzAis5itZNqkjZQgo7oCSu3jIuk9OkdNGQhlA=,tag:CWuNrno+zGR3YDG5JjWYnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
