# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:BXTBy2s4cfdvgyW7UxFekZ9MuW1mbdCtAruFqRXP4i+a/QODli3YlJSupqH0NKJuQqpqQyC9OrZWjgVj/Sgiow2UqLUN6ZxIzfizYKaSGRnUb0yPqDI1eMRFHix2zntaN3DIP2LdkceuJ6IyE6cB2gIFySujMyBZU5g0KdQvPj1uHgxZVAEkuGVfmeFkN73V95zs5OAEzbkzJajT8MP8,iv:0rdyk7E+prwtwxhg2pSHvvBn7NjO5ISSPDrXBD0dRdo=,tag:uroqjYBZSaDZAwRMptvRcA==,type:str]
    #ENC[AES256_GCM,data:xDiuWJkEaWono81K76guZJE4bEBTClhw+Blt2NxWNpRvghuBiYhGkws/7ipOnP45dYRoiV5vh5NOqpsRDWzRd/hfbmG2pXneguw//all5J261H6TJ+OJAhJIlI8Udyc6KaoY9Iu2fNqAVdoyf/UX32objDx2EZqloPMPaIZhxpgVt/3RZHicbRZVq0WwRaqd1pXSAfkMD8A4nEqBMc9klwJwoNM8mG/iedgHDrIs2sU+WGtk3dbImj7DoSxlGA==,iv:XgUAzHLczmullS/Izm3ypdgaj2Ei9f5HWhjGQUaP8cg=,tag:Skuo7BNXt1Zdg2J0dz5SbA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-03T10:33:38Z"
    mac: ENC[AES256_GCM,data:kayFFTQJZR3+E6xZJAy2nr2HgYy2F+8WrWDmSNxiMNNa4UbglWXtL6lrcEJEDznX19HMiXmcl+9cV1YKUySJ/89eoxRSBuOqafuDF0uiqaxkcGtx61ZlKt0dQm9xyufZ6yccDTg7K3lFD3TTpjIl27cG7K3DqIYMYt/Q25815wg=,iv:byoOlZeZ4cLRJy7y7YobiRWfKrwVw0Zw3SmaXn1wfjc=,tag:efps/Oz3Ig1VqZSKY50ENw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
