# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:xVsfX3xotxs9/fgAnfbGx4uP52gybXZa9tmPupG3NzUCLc3PT6dCTNb4BpxdCdyVL8hB3tWIlDYwZ+GISC1UAo5XvmYypH4aX50sZobV5xEvn2Ak+yUO8IEfmeRFmq5SZlD+p8TSLziRMPevnxWnQ2Ert3f8/pB6zzj799+kYIzNVjOy9mC8AKCzT/USBgcNEp+qLLpXUUoxBV+4ND2HbmJ6enWnZ3fuHtXYj1BEq66I2A==,iv:REty58S4qoO84VaVcHCLLf2dk2hEJBUA2GraM0JBMvA=,tag:LNtNu/BFxZeGoPO8SQWg9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnBhSjZrRktua2xIemtn
            eW5ZVzV1V1FVY1dCeXNONkZ4bVRBZndNaGdvCkU3dEI4MmYwT2xZeGVnUUtmWFZT
            NFZtUHdlRVdNUTZoZ25xUUNMSVF1TDQKLS0tIEYveW52dFhnSUJkYy9hTW1wSVN3
            bVVPTjdqTFNMZW9Jb0xJNVZBazdGK0EKXYRFapYidFVsX76q/MvNu88Vz7CH3x4c
            d0tenkEYy6NDlYCvwm3QvzY1SOqbJYC0Fmbotv5yzWgsx1f7+kEKKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T11:12:15Z"
    mac: ENC[AES256_GCM,data:y6mlZif9Sbn25yYf4PMi5BiL4KHf10THQb0obJrPH+cHhPuj+ZxwqKMEk2toFQNrxkIVL9ptQL5biqckoODdw2+/JtTJLQEydFKl2Kg4y7irdiASZPK74H6KJHRb/LF7HNzk/gOM6lXluNVK66kC7s2TrpQOJXWiNYKFefRvsIQ=,iv:01bS0/x31YI7cDlDS3Gpslo3C9/t+fAUZQPJQuVxnDI=,tag:bi+Jh9SAskxM8LLzTEI7iA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
