---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: tailscale-auth
  data:
    - remoteRef:
        key: TAILSCALE_AUTHKEY
      secretKey: TS_AUTHKEY
