---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-home-assistant
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-mosquitto
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-external-secrets
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/home/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant
      namespace: home
  interval: 15m
  retryInterval: 1m
  timeout: 5m
