---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        adminUser: "{{ .GF_ADMIN_USER }}"
        adminPassword: "{{ .GF_ADMIN_PASS }}"
        # App
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_HOST: &dbHost postgres-rw.databases.svc.cluster.local
        GF_DATABASE_USER: "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: "{{ .GF_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .GF_DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - find:
        path: GF_
    - find:
        path: POSTGRES_
