---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-secrets
  target:
    name: github-webhook-token-secret
  data:
    - remoteRef:
        key: GITHUB_WEBHOOK_TOKEN
      secretKey: token
