---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tailscale-gateway
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    serviceAccount:
      name: tailscale

    image:
      repository: ghcr.io/tailscale/tailscale
      tag: v1.44.0
    env:
      TZ: ${TIMEZONE}
      PORT: &port ${SECRET_PUBLIC_PORT}
      TS_KUBE_SECRET: "tailscale-auth"
      SA_NAME: tailscale
      TS_USERSPACE: "true"
      TS_ROUTES: ${SECRET_IOT_CIDR}
      TS_EXTRA_ARGS: "--advertise-exit-node"
    envFrom:
      - secretRef:
          name: tailscale-auth

    service:
      main:
        enabled: false
      tailnet:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_TAILSCALE_ADDR}
        externalTrafficPolicy: Local
        ports:
          tailnet:
            enabled: true
            port: *port
            protocol: UDP
            targetPort: *port

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000

    ingress:
      main:
        enabled: false
