# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: networking
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:rREXWp2KbMkVrNbyy/kNVTOiX6QIGhhI5gFhK3FeJZKlN72F0ZQlnkwh/Lhr1BnJj80ZdRbrnZT2,iv:WI2ZNp710rAegJjbrwhCMHLlLv4HDVycTFG0ccLwc5s=,tag:Gnp5Nsd1C9/UPJsTxZhF/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wvlv68u3uadfpjvluuydng2xj726pa4j5lzfzrp5z4333c2tv5fsftppun
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZFc0RStRYXNRUm0rQ2pG
            dDJmbjFpMzVBZmw5QU8zR2M4cUtzUlE5L0NFCjhCbktQN0E3TWJVb0laWEFPT1Vj
            bis3bXVlSFBxejRFbUZRZHpsU0FNR2cKLS0tIG9ETGhrRCtRWDJmWHB4a1R0Um5p
            S00rRTROOG5EM0RGMTZaSGpSSUFsWWMKZncDS3+jT2qYA+KY9EZ7qMaxdaHKuTFM
            3ExPleQcdUZ07mOHqiYS8dm+/5Lpf8AwTSSXGqSWzfwAmXyDZ1Chfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T09:48:31Z"
    mac: ENC[AES256_GCM,data:nVYjeLCQyx9rY+gb+lUVBN9pUP9/NlhWKk53hgg50i3dykAW/8WGabu4Vw3vfSfH3AYvotJcydHF4FlwMkWC/m96AA7mHk9c7juf3X8+C3AIVJJBr9KoFLo2DWq5asyvORW+LYRb22AS5yhEp24LqRI4/gGAjD83KTT2Ifm9+wY=,iv:wYcshdNOc40cpXluQICY3Q50mHk4LJvF6CSQCtqJ3Ag=,tag:yTsOIopQtab8I1SIR8KdmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
