---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./config-pvc.yaml
  - ./helmrelease.yaml
  - ../../../../templates/volsync
labels:
  - pairs:
      app.kubernetes.io/name: unifi
      app.kubernetes.io/instance: unifi
