---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.0.17
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 1
    recreatePods: true
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${SECRET_EMQX_DEFAULT_PASSWORD}
      EMQX_AUTH__USER__1__USERNAME: ${SECRET_EMQX_USER}
      EMQX_AUTH__USER__1__PASSWORD: ${SECRET_EMQX_USER_PASSWORD}
    service:
      type: LoadBalancer
      annotations:
        coredns.io/hostname: mqtt.${SECRET_DOMAIN}
      externalIPs: ["${SVC_EMQX_ADDR}"]
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/appName: "EMQX"
          hajimari.io/icon: simple-icons:eclipsemosquitto
        path: /
        pathType: Prefix
        hosts:
          - &host mqtt.${SECRET_DOMAIN}
        tls:
          - hosts:
              - *host
    metrics:
      enabled: false
    persistence:
      enabled: true
      storageClassName: local-path
      size: 100Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["emqx"]
              topologyKey: kubernetes.io/hostname
