---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-nfs
spec:
  storageClassName: frigate
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NAS_IP}
    path: ${SECRET_FRIGATE_NFS_PATH}
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-nfs
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: frigate
  resources:
    requests:
      storage: 1Mi
